import { SinglePlayerStageInfo, GameMode, Player, SinglePlayerLevel, LeagueRewardTier } from '../types.js';

// Data transcribed from the user-provided image
export const TOWER_STAGES: SinglePlayerStageInfo[] = [
    // 1-10 Floors
    { id: 'tower-1', floor: 1, name: '1층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, katagoLevel: 10, placements: { black: 2, white: 2, blackPattern: 0, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-2', floor: 2, name: '2층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, katagoLevel: 10, placements: { black: 2, white: 3, blackPattern: 0, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-3', floor: 3, name: '3층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, katagoLevel: 10, placements: { black: 2, white: 3, blackPattern: 1, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-4', floor: 4, name: '4층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 5, white: 5 }, katagoLevel: 10, placements: { black: 2, white: 4, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-5', floor: 5, name: '5층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, katagoLevel: 10, placements: { black: 2, white: 5, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 30, items: [{itemId: "골드 꾸러미1", quantity: 1}] }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-6', floor: 6, name: '6층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, katagoLevel: 10, placements: { black: 3, white: 7, blackPattern: 2, whitePattern: 0, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-7', floor: 7, name: '7층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, katagoLevel: 10, placements: { black: 3, white: 6, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-8', floor: 8, name: '8층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, katagoLevel: 10, placements: { black: 3, white: 7, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-9', floor: 9, name: '9층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 6, white: 6 }, katagoLevel: 10, placements: { black: 3, white: 6, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 90 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 100, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-10', floor: 10, name: '10층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 7, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 7, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 100, items: [{itemId: "장비 상자 I", quantity: 1}] }, repeatClear: { gold: 10, exp: 15 } }, blackStoneLimit: 15 },
    
    // 11-20 Floors
    { id: 'tower-11', floor: 11, name: '11층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 7, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 7, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-12', floor: 12, name: '12층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 7, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 6, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-13', floor: 13, name: '13층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 7, white: 7 }, katagoLevel: 10, placements: { black: 3, white: 6, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-14', floor: 14, name: '14층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 7, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 6, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-15', floor: 15, name: '15층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 8, white: 8 }, katagoLevel: 10, placements: { black: 4, white: 8, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 30, items: [{itemId: "재료 상자 I", quantity: 1}] }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-16', floor: 16, name: '16층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 8, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 6, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-17', floor: 17, name: '17층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 8, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 6, blackPattern: 4, whitePattern: 4, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-18', floor: 18, name: '18층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 8, white: 7 }, katagoLevel: 10, placements: { black: 4, white: 7, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-19', floor: 19, name: '19층', level: SinglePlayerLevel.입문, actionPointCost: 2, boardSize: 7, targetScore: { black: 8, white: 8 }, katagoLevel: 10, placements: { black: 5, white: 9, blackPattern: 2, whitePattern: 4, centerBlackStoneChance: 80 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 150, exp: 20 }, repeatClear: { gold: 10, exp: 10 } }, blackStoneLimit: 15 },
    { id: 'tower-20', floor: 20, name: '20층', level: SinglePlayerLevel.입문, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, katagoLevel: 10, placements: { black: 4, white: 6, blackPattern: 2, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 100, items: [{itemId: "다이아 꾸러미1", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },

    // 21-30 Floors
    { id: 'tower-21', floor: 21, name: '21층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 30 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-22', floor: 22, name: '22층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 2, whitePattern: 2, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 30 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-23', floor: 23, name: '23층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, katagoLevel: 10, placements: { black: 5, white: 9, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 30 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-24', floor: 24, name: '24층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 9, white: 8 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 30 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-25', floor: 25, name: '25층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, katagoLevel: 10, placements: { black: 3, white: 9, blackPattern: 4, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 50, items: [{itemId: "골드 꾸러미2", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-26', floor: 26, name: '26층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, katagoLevel: 10, placements: { black: 3, white: 10, blackPattern: 4, whitePattern: 2, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 40 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-27', floor: 27, name: '27층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 40 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-28', floor: 28, name: '28층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, katagoLevel: 10, placements: { black: 5, white: 8, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 200, exp: 40 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-29', floor: 29, name: '29층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 10, white: 9 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 3, whitePattern: 1, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 100, items: [{itemId: "장비 상자 II", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-30', floor: 30, name: '30층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, katagoLevel: 10, placements: { black: 6, white: 11, blackPattern: 2, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 50, items: [{itemId: '장비 상자 III', quantity: 1}]}, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    
    // 31-40 Floors
    { id: 'tower-31', floor: 31, name: '31층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, katagoLevel: 10, placements: { black: 6, white: 10, blackPattern: 2, whitePattern: 1, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 50 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-32', floor: 32, name: '32층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, katagoLevel: 10, placements: { black: 6, white: 9, blackPattern: 1, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 50 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-33', floor: 33, name: '33층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, katagoLevel: 10, placements: { black: 6, white: 10, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 50 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-34', floor: 34, name: '34층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 11, white: 9 }, katagoLevel: 10, placements: { black: 6, white: 10, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 50 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-35', floor: 35, name: '35층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, katagoLevel: 10, placements: { black: 6, white: 11, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 100, items: [{itemId: "재료 상자 II", quantity: 1}] }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-36', floor: 36, name: '36층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, katagoLevel: 10, placements: { black: 6, white: 10, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 60 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-37', floor: 37, name: '37층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, katagoLevel: 10, placements: { black: 3, white: 9, blackPattern: 4, whitePattern: 3, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 60 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-38', floor: 38, name: '38층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, katagoLevel: 10, placements: { black: 4, white: 11, blackPattern: 3, whitePattern: 1, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 60 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-39', floor: 39, name: '39층', level: SinglePlayerLevel.초급, actionPointCost: 3, boardSize: 9, targetScore: { black: 12, white: 10 }, katagoLevel: 10, placements: { black: 6, white: 10, blackPattern: 1, whitePattern: 2, centerBlackStoneChance: 70 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 250, exp: 60 }, repeatClear: { gold: 30, exp: 20 } }, blackStoneLimit: 18 },
    { id: 'tower-40', floor: 40, name: '40층', level: SinglePlayerLevel.초급, actionPointCost: 4, boardSize: 9, targetScore: { black: 15, white: 12 }, katagoLevel: 10, placements: { black: 4, white: 11, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 150, items: [{itemId: "다이아 꾸러미2", quantity: 1}] }, repeatClear: { gold: 40, exp: 30 } }, blackStoneLimit: 18 },
    
    // 41-50 Floors
    { id: 'tower-41', floor: 41, name: '41층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 15, white: 12 }, katagoLevel: 10, placements: { black: 3, white: 11, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-42', floor: 42, name: '42층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 15, white: 12 }, katagoLevel: 10, placements: { black: 4, white: 10, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-43', floor: 43, name: '43층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 15, white: 12 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-44', floor: 44, name: '44층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 15, white: 12 }, katagoLevel: 10, placements: { black: 5, white: 11, blackPattern: 3, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-45', floor: 45, name: '45층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 15, white: 12 }, katagoLevel: 10, placements: { black: 5, white: 14, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-46', floor: 46, name: '46층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 16, white: 12 }, katagoLevel: 10, placements: { black: 5, white: 10, blackPattern: 4, whitePattern: 5, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-47', floor: 47, name: '47층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 16, white: 12 }, katagoLevel: 10, placements: { black: 5, white: 13, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-48', floor: 48, name: '48층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 16, white: 12 }, katagoLevel: 10, placements: { black: 2, white: 12, blackPattern: 7, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 300, exp: 100 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-49', floor: 49, name: '49층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 16, white: 12 }, katagoLevel: 10, placements: { black: 3, white: 13, blackPattern: 6, whitePattern: 4, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 200, items: [{itemId: '장비 상자 III', quantity: 1}]}, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-50', floor: 50, name: '50층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 17, white: 13 }, katagoLevel: 10, placements: { black: 5, white: 14, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    
    // 51-60 Floors
    { id: 'tower-51', floor: 51, name: '51층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 17, white: 13 }, katagoLevel: 10, placements: { black: 4, white: 14, blackPattern: 5, whitePattern: 2, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-52', floor: 52, name: '52층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 17, white: 13 }, katagoLevel: 10, placements: { black: 5, white: 12, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-53', floor: 53, name: '53층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 17, white: 13 }, katagoLevel: 10, placements: { black: 6, white: 14, blackPattern: 3, whitePattern: 2, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-54', floor: 54, name: '54층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 17, white: 13 }, katagoLevel: 10, placements: { black: 6, white: 12, blackPattern: 2, whitePattern: 3, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-55', floor: 55, name: '55층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 18, white: 13 }, katagoLevel: 10, placements: { black: 5, white: 12, blackPattern: 3, whitePattern: 5, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 200, items: [{itemId: "재료 상자 III", quantity: 1}]}, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-56', floor: 56, name: '56층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 18, white: 13 }, katagoLevel: 10, placements: { black: 7, white: 14, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-57', floor: 57, name: '57층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 18, white: 13 }, katagoLevel: 10, placements: { black: 8, white: 16, blackPattern: 1, whitePattern: 0, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-58', floor: 58, name: '58층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 18, white: 13 }, katagoLevel: 10, placements: { black: 6, white: 14, blackPattern: 4, whitePattern: 3, centerBlackStoneChance: 50 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-59', floor: 59, name: '59층', level: SinglePlayerLevel.중급, actionPointCost: 4, boardSize: 11, targetScore: { black: 18, white: 13 }, katagoLevel: 10, placements: { black: 4, white: 15, blackPattern: 6, whitePattern: 2, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 400, exp: 150 }, repeatClear: { gold: 50, exp: 30 } }, blackStoneLimit: 20 },
    { id: 'tower-60', floor: 60, name: '60층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 2, white: 14, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 250, items: [{itemId: '다이아 꾸러미3', quantity: 1}]}, repeatClear: { gold: 60, exp: 40 } }, blackStoneLimit: 25 },
    
    // 61-70 Floors
    { id: 'tower-61', floor: 61, name: '61층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 1, white: 15, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-62', floor: 62, name: '62층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 2, white: 16, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-63', floor: 63, name: '63층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 3, white: 18, blackPattern: 6, whitePattern: 1, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-64', floor: 64, name: '64층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 17, blackPattern: 7, whitePattern: 5, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-65', floor: 65, name: '65층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 5, white: 17, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-66', floor: 66, name: '66층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 6, white: 16, blackPattern: 5, whitePattern: 5, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-67', floor: 67, name: '67층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 14, blackPattern: 5, whitePattern: 5, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-68', floor: 68, name: '68층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 18, blackPattern: 6, whitePattern: 2, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-69', floor: 69, name: '69층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 5, white: 16, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 500, exp: 300, items: [{itemId: '장비 상자 IV', quantity: 1}]}, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-70', floor: 70, name: '70층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 5, white: 18, blackPattern: 5, whitePattern: 2, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    
    // 71-80 Floors
    { id: 'tower-71', floor: 71, name: '71층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 17, blackPattern: 6, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-72', floor: 72, name: '72층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 5, white: 19, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-73', floor: 73, name: '73층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 3, white: 15, blackPattern: 4, whitePattern: 2, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-74', floor: 74, name: '74층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 14, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-75', floor: 75, name: '75층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 3, white: 18, blackPattern: 5, whitePattern: 0, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 250, items: [{itemId: '재료 상자 IV', quantity: 1}]}, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-76', floor: 76, name: '76층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 17, blackPattern: 5, whitePattern: 2, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-77', floor: 77, name: '77층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 5, white: 18, blackPattern: 4, whitePattern: 1, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-78', floor: 78, name: '78층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 3, white: 16, blackPattern: 6, whitePattern: 3, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-79', floor: 79, name: '79층', level: SinglePlayerLevel.고급, actionPointCost: 5, boardSize: 13, targetScore: { black: 20, white: 15 }, katagoLevel: 10, placements: { black: 4, white: 16, blackPattern: 7, whitePattern: 5, centerBlackStoneChance: 40 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 600, exp: 200 }, repeatClear: { gold: 100, exp: 40 } }, blackStoneLimit: 25 },
    { id: 'tower-80', floor: 80, name: '80층', level: SinglePlayerLevel.고급, actionPointCost: 6, boardSize: 13, targetScore: { black: 25, white: 20 }, katagoLevel: 10, placements: { black: 5, white: 16, blackPattern: 6, whitePattern: 6, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 350, items: [{itemId: '다이아 꾸러미4', quantity: 1}]}, repeatClear: { gold: 80, exp: 50 } }, blackStoneLimit: 25 },
    
    // 81-90 Floors
    { id: 'tower-81', floor: 81, name: '81층', level: SinglePlayerLevel.유단자, actionPointCost: 6, boardSize: 13, targetScore: { black: 25, white: 20 }, katagoLevel: 10, placements: { black: 4, white: 16, blackPattern: 5, whitePattern: 4, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-82', floor: 82, name: '82층', level: SinglePlayerLevel.유단자, actionPointCost: 6, boardSize: 13, targetScore: { black: 25, white: 19 }, katagoLevel: 10, placements: { black: 3, white: 16, blackPattern: 5, whitePattern: 3, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-83', floor: 83, name: '83층', level: SinglePlayerLevel.유단자, actionPointCost: 6, boardSize: 13, targetScore: { black: 25, white: 18 }, katagoLevel: 10, placements: { black: 2, white: 16, blackPattern: 7, whitePattern: 4, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-84', floor: 84, name: '84층', level: SinglePlayerLevel.유단자, actionPointCost: 6, boardSize: 13, targetScore: { black: 25, white: 17 }, katagoLevel: 10, placements: { black: 3, white: 18, blackPattern: 6, whitePattern: 2, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 150, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-85', floor: 85, name: '85층', level: SinglePlayerLevel.유단자, actionPointCost: 6, boardSize: 13, targetScore: { black: 25, white: 16 }, katagoLevel: 10, placements: { black: 0, white: 17, blackPattern: 8, whitePattern: 2, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 400, items: [{itemId: '재료 상자 V', quantity: 1}]}, repeatClear: { gold: 150, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-86', floor: 86, name: '86층', level: SinglePlayerLevel.유단자, actionPointCost: 7, boardSize: 13, targetScore: { black: 25, white: 15 }, katagoLevel: 10, placements: { black: 2, white: 19, blackPattern: 8, whitePattern: 2, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 200, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-87', floor: 87, name: '87층', level: SinglePlayerLevel.유단자, actionPointCost: 7, boardSize: 13, targetScore: { black: 25, white: 14 }, katagoLevel: 10, placements: { black: 4, white: 19, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 700, exp: 250 }, repeatClear: { gold: 200, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-88', floor: 88, name: '88층', level: SinglePlayerLevel.유단자, actionPointCost: 7, boardSize: 13, targetScore: { black: 25, white: 13 }, katagoLevel: 10, placements: { black: 5, white: 20, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 200, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-89', floor: 89, name: '89층', level: SinglePlayerLevel.유단자, actionPointCost: 7, boardSize: 13, targetScore: { black: 25, white: 12 }, katagoLevel: 10, placements: { black: 4, white: 20, blackPattern: 8, whitePattern: 3, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 200, exp: 50 } }, blackStoneLimit: 25 },
    { id: 'tower-90', floor: 90, name: '90층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 30, white: 15 }, katagoLevel: 10, placements: { black: 1, white: 20, blackPattern: 12, whitePattern: 3, centerBlackStoneChance: 20 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 500, items: [{itemId: "장비 상자 V", quantity: 1}] }, repeatClear: { gold: 300, exp: 90 } }, blackStoneLimit: 25 },
    
    // 91-100 Floors
    { id: 'tower-91', floor: 91, name: '91층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 30, white: 15 }, katagoLevel: 10, placements: { black: 2, white: 17, blackPattern: 8, whitePattern: 4, centerBlackStoneChance: 20 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-92', floor: 92, name: '92층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 30, white: 15 }, katagoLevel: 10, placements: { black: 3, white: 18, blackPattern: 9, whitePattern: 5, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-93', floor: 93, name: '93층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 30, white: 15 }, katagoLevel: 10, placements: { black: 3, white: 20, blackPattern: 10, whitePattern: 4, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 300 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-94', floor: 94, name: '94층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 30, white: 15 }, katagoLevel: 10, placements: { black: 5, white: 21, blackPattern: 6, whitePattern: 1, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 400, items: [{itemId: '재료 상자 VI', quantity: 1}]}, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-95', floor: 95, name: '95층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 35, white: 18 }, katagoLevel: 10, placements: { black: 4, white: 22, blackPattern: 7, whitePattern: 0, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-96', floor: 96, name: '96층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 35, white: 18 }, katagoLevel: 10, placements: { black: 3, white: 20, blackPattern: 8, whitePattern: 3, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-97', floor: 97, name: '97층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 35, white: 18 }, katagoLevel: 10, placements: { black: 5, white: 16, blackPattern: 3, whitePattern: 3, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-98', floor: 98, name: '98층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 35, white: 18 }, katagoLevel: 10, placements: { black: 4, white: 19, blackPattern: 7, whitePattern: 3, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350 }, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-99', floor: 99, name: '99층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 35, white: 18 }, katagoLevel: 10, placements: { black: 3, white: 21, blackPattern: 8, whitePattern: 1, centerBlackStoneChance: 30 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 800, exp: 350, items: [{itemId: '장비 상자 VI', quantity: 1}]}, repeatClear: { gold: 300, exp: 50 } }, blackStoneLimit: 30 },
    { id: 'tower-100', floor: 100, name: '100층', level: SinglePlayerLevel.유단자, actionPointCost: 8, boardSize: 13, targetScore: { black: 50, white: 30 }, katagoLevel: 10, placements: { black: 4, white: 18, blackPattern: 6, whitePattern: 3, centerBlackStoneChance: 10 }, timeControl: { type: 'byoyomi', mainTime: 1, byoyomiTime: 30, byoyomiCount: 3 }, rewards: { firstClear: { gold: 1000, exp: 1000, items: [{itemId: '장비 상자 VI', quantity: 1}] }, repeatClear: { gold: 300, exp: 100 } }, blackStoneLimit: 30 },
];

export const TOWER_RANKING_REWARDS: LeagueRewardTier[] = [
    { rankStart: 1, rankEnd: 1, diamonds: 200, items: [{ itemId: '장비 상자 IV', quantity: 1 }, { itemId: '재료 상자 IV', quantity: 1 }], outcome: 'maintain' },
    { rankStart: 2, rankEnd: 2, diamonds: 150, items: [{ itemId: '장비 상자 III', quantity: 1 }, { itemId: '재료 상자 III', quantity: 1 }], outcome: 'maintain' },
    { rankStart: 3, rankEnd: 10, diamonds: 100, items: [{ itemId: '장비 상자 II', quantity: 1 }, { itemId: '재료 상자 II', quantity: 1 }], outcome: 'maintain' },
    { rankStart: 11, rankEnd: 50, diamonds: 75, items: [{ itemId: '장비 상자 I', quantity: 1 }, { itemId: '재료 상자 I', quantity: 1 }], outcome: 'maintain' },
    { rankStart: 51, rankEnd: 100, diamonds: 50, items: [{ itemId: '골드 꾸러미2', quantity: 1 }], outcome: 'maintain' },
    { rankStart: 101, rankEnd: Infinity, diamonds: 25, outcome: 'maintain' },
];
