import { createDefaultQuests, createDefaultBaseStats, createDefaultSpentStatPoints, defaultStats } from '../initialData.js';
import * as types from '../../types.js';
import { DEFAULT_GAME_SETTINGS } from '../../constants.js';

const safeParse = (jsonString: string | null | undefined, defaultValue: any, contextId: string, fieldName: string) => {
    if (jsonString === null || jsonString === undefined) return defaultValue;
    try {
        if (typeof jsonString === 'string' && jsonString.trim() === '') return defaultValue;
        // The value might already be an object if it comes from a non-DB source, so check before parsing.
        if (typeof jsonString === 'object') return jsonString;
        const parsed = JSON.parse(jsonString);
        return parsed === null ? defaultValue : parsed;
    } catch (e) {
        console.warn(`[DB Mapper] Malformed JSON for ID ${contextId}, field ${fieldName}. Falling back to default. Data: "${jsonString}"`);
        return defaultValue;
    }
};

export const rowToUser = (row: any): types.User | null => {
    if (!row) return null;
    try {
        const defaultQuests = createDefaultQuests();
        const questsFromDb = safeParse(row.quests, {}, row.id, 'quests');
        
        const quests: types.QuestLog = {
            daily: {
                ...(defaultQuests.daily || {}),
                ...(questsFromDb.daily || {}),
                quests: questsFromDb.daily?.quests ?? defaultQuests.daily?.quests ?? [],
                claimedMilestones: questsFromDb.daily?.claimedMilestones ?? defaultQuests.daily?.claimedMilestones ?? [false, false, false, false, false],
            },
            weekly: {
                ...(defaultQuests.weekly || {}),
                ...(questsFromDb.weekly || {}),
                quests: questsFromDb.weekly?.quests ?? defaultQuests.weekly?.quests ?? [],
                claimedMilestones: questsFromDb.weekly?.claimedMilestones ?? defaultQuests.weekly?.claimedMilestones ?? [false, false, false, false, false],
            },
            monthly: {
                 ...(defaultQuests.monthly || {}),
                 ...(questsFromDb.monthly || {}),
                 quests: questsFromDb.monthly?.quests ?? defaultQuests.monthly?.quests ?? [],
                 claimedMilestones: questsFromDb.monthly?.claimedMilestones ?? defaultQuests.monthly?.claimedMilestones ?? [false, false, false, false, false],
            }
        };

        const actionPointsFromDb = safeParse(row.actionPoints, {}, row.id, 'actionPoints');
        const actionPoints = {
            current: typeof actionPointsFromDb.current === 'number' ? actionPointsFromDb.current : 30,
            max: typeof actionPointsFromDb.max === 'number' ? actionPointsFromDb.max : 30,
        };

        const user: types.User = {
            id: row.id,
            username: row.username,
            nickname: row.nickname,
            isAdmin: !!row.isAdmin,
            strategyLevel: row.strategyLevel ?? 1,
            strategyXp: row.strategyXp ?? 0,
            playfulLevel: row.playfulLevel ?? 1,
            playfulXp: row.playfulXp ?? 0,
            gold: row.gold ?? 0,
            diamonds: row.diamonds ?? 0,
            inventorySlots: row.inventorySlots ?? 40,
            chatBanUntil: row.chatBanUntil ?? undefined,
            connectionBanUntil: row.connectionBanUntil ?? undefined,
            lastActionPointUpdate: row.lastActionPointUpdate ?? 0,
            actionPointPurchasesToday: row.actionPointPurchasesToday ?? undefined,
            lastActionPointPurchaseDate: row.lastActionPointPurchaseDate ?? undefined,
            avatarId: row.avatarId || 'profile_1',
            borderId: row.borderId || 'default',
            ownedBorders: safeParse(row.ownedBorders, ['default'], row.id, 'ownedBorders'),
            tournamentScore: row.tournamentScore ?? 1200,
            league: row.league || types.LeagueTier.Sprout,
            mannerMasteryApplied: !!row.mannerMasteryApplied,
            mannerScore: row.mannerScore ?? 200,
            pendingPenaltyNotification: row.pendingPenaltyNotification ?? undefined,
            previousSeasonTier: row.previousSeasonTier ?? undefined,
            stats: { ...defaultStats, ...safeParse(row.stats, {}, row.id, 'stats') },
            baseStats: { ...createDefaultBaseStats(), ...safeParse(row.baseStats, {}, row.id, 'baseStats') },
            spentStatPoints: { ...createDefaultSpentStatPoints(), ...safeParse(row.spentStatPoints, {}, row.id, 'spentStatPoints') },
            inventory: safeParse(row.inventory, [], row.id, 'inventory'),
            equipment: safeParse(row.equipment, {}, row.id, 'equipment'),
            actionPoints,
            mail: safeParse(row.mail, [], row.id, 'mail'),
            quests,
            seasonHistory: safeParse(row.seasonHistory, {}, row.id, 'seasonHistory'),
            dailyShopPurchases: safeParse(row.dailyShopPurchases, {}, row.id, 'dailyShopPurchases'),
            lastNeighborhoodPlayedDate: row.lastNeighborhoodPlayedDate ?? undefined,
            dailyNeighborhoodWins: row.dailyNeighborhoodWins ?? 0,
            neighborhoodRewardClaimed: !!row.neighborhoodRewardClaimed,
            lastNeighborhoodTournament: safeParse(row.lastNeighborhoodTournament, null, row.id, 'lastNeighborhoodTournament'),
            lastNationalPlayedDate: row.lastNationalPlayedDate ?? undefined,
            dailyNationalWins: row.dailyNationalWins ?? 0,
            nationalRewardClaimed: !!row.nationalRewardClaimed,
            lastNationalTournament: safeParse(row.lastNationalTournament, null, row.id, 'lastNationalTournament'),
            lastWorldPlayedDate: row.lastWorldPlayedDate ?? undefined,
            dailyWorldWins: row.dailyWorldWins ?? 0,
            worldRewardClaimed: !!row.worldRewardClaimed,
            lastWorldTournament: safeParse(row.lastWorldTournament, null, row.id, 'lastWorldTournament'),
            weeklyCompetitors: safeParse(row.weeklyCompetitors, [], row.id, 'weeklyCompetitors'),
            lastWeeklyCompetitorsUpdate: row.lastWeeklyCompetitorsUpdate ?? undefined,
            lastLeagueUpdate: row.lastLeagueUpdate ?? undefined,
            monthlyGoldBuffExpiresAt: row.monthlyGoldBuffExpiresAt ?? undefined,
            mbti: row.mbti ?? undefined,
            isMbtiPublic: !!row.isMbtiPublic,
            singlePlayerProgress: row.singlePlayerProgress ?? 0,
            bonusStatPoints: row.bonusStatPoints ?? 0,
            singlePlayerMissions: safeParse(row.singlePlayerMissions, {}, row.id, 'singlePlayerMissions'),
            towerProgress: safeParse(row.towerProgress, { highestFloor: 0, lastClearTimestamp: 0 }, row.id, 'towerProgress'),
            claimedFirstClearRewards: safeParse(row.claimedFirstClearRewards, [], row.id, 'claimedFirstClearRewards'),
        };
        return user;
    } catch (e) {
        console.error(`[FATAL] Unrecoverable error processing user data for row ID ${row?.id}:`, e);
        return null;
    }
};

export const rowToGame = (row: any): types.LiveGameSession | null => {
    if (!row) return null;
    try {
        const game: types.LiveGameSession = {
            id: row.id,
            mode: row.mode,
            description: row.description ?? undefined,
            player1: safeParse(row.player1, null, row.id, 'player1'),
            player2: safeParse(row.player2, null, row.id, 'player2'),
            blackPlayerId: row.blackPlayerId ?? null,
            whitePlayerId: row.whitePlayerId ?? null,
            gameStatus: row.gameStatus,
            currentPlayer: row.currentPlayer,
            boardState: safeParse(row.boardState, [], row.id, 'boardState'),
            moveHistory: safeParse(row.moveHistory, [], row.id, 'moveHistory'),
            captures: safeParse(row.captures, {}, row.id, 'captures'),
            baseStoneCaptures: safeParse(row.baseStoneCaptures, {}, row.id, 'baseStoneCaptures'),
            hiddenStoneCaptures: safeParse(row.hiddenStoneCaptures, {}, row.id, 'hiddenStoneCaptures'),
            winner: row.winner ?? null,
            winReason: row.winReason ?? null,
            finalScores: safeParse(row.finalScores, null, row.id, 'finalScores'),
            createdAt: row.createdAt,
            lastMove: safeParse(row.lastMove, null, row.id, 'lastMove'),
            lastTurnStones: safeParse(row.lastTurnStones, null, row.id, 'lastTurnStones'),
            stonesPlacedThisTurn: safeParse(row.stonesPlacedThisTurn, null, row.id, 'stonesPlacedThisTurn'),
            passCount: row.passCount ?? 0,
            koInfo: safeParse(row.koInfo, null, row.id, 'koInfo'),
            winningLine: safeParse(row.winningLine, null, row.id, 'winningLine'),
            statsUpdated: !!row.statsUpdated,
            summary: safeParse(row.summary, null, row.id, 'summary'),
            animation: safeParse(row.animation, null, row.id, 'animation'),
            blackTimeLeft: row.blackTimeLeft,
            whiteTimeLeft: row.whiteTimeLeft,
            blackByoyomiPeriodsLeft: row.blackByoyomiPeriodsLeft,
            whiteByoyomiPeriodsLeft: row.whiteByoyomiPeriodsLeft,
            turnDeadline: row.turnDeadline ?? undefined,
            turnStartTime: row.turnStartTime ?? undefined,
            disconnectionState: safeParse(row.disconnectionState, null, row.id, 'disconnectionState'),
            disconnectionCounts: safeParse(row.disconnectionCounts, {}, row.id, 'disconnectionCounts'),
            noContestInitiatorIds: safeParse(row.noContestInitiatorIds, null, row.id, 'noContestInitiatorIds'),
            currentActionButtons: safeParse(row.currentActionButtons, {}, row.id, 'currentActionButtons'),
            actionButtonCooldownDeadline: safeParse(row.actionButtonCooldownDeadline, null, row.id, 'actionButtonCooldownDeadline'),
            actionButtonUses: safeParse(row.actionButtonUses, null, row.id, 'actionButtonUses'),
            maxActionButtonUses: row.maxActionButtonUses ?? undefined,
            actionButtonUsedThisCycle: safeParse(row.actionButtonUsedThisCycle, null, row.id, 'actionButtonUsedThisCycle'),
            mannerScoreChanges: safeParse(row.mannerScoreChanges, {}, row.id, 'mannerScoreChanges'),
            nigiri: safeParse(row.nigiri, null, row.id, 'nigiri'),
            guessDeadline: row.guessDeadline ?? undefined,
            bids: safeParse(row.bids, null, row.id, 'bids'),
            biddingRound: row.biddingRound ?? undefined,
            captureBidDeadline: row.captureBidDeadline ?? undefined,
            effectiveCaptureTargets: safeParse(row.effectiveCaptureTargets, null, row.id, 'effectiveCaptureTargets'),
            baseStones: safeParse(row.baseStones, null, row.id, 'baseStones'),
            baseStones_p1: safeParse(row.baseStones_p1, null, row.id, 'baseStones_p1'),
            baseStones_p2: safeParse(row.baseStones_p2, null, row.id, 'baseStones_p2'),
            basePlacementDeadline: row.basePlacementDeadline ?? undefined,
            komiBids: safeParse(row.komiBids, null, row.id, 'komiBids'),
            komiBiddingDeadline: row.komiBiddingDeadline ?? undefined,
            komiBiddingRound: row.komiBiddingRound ?? undefined,
            komiBidRevealProcessed: !!row.komiBidRevealProcessed,
            finalKomi: row.finalKomi ?? undefined,
            hiddenMoves: safeParse(row.hiddenMoves, null, row.id, 'hiddenMoves'),
            scans_p1: row.scans_p1 ?? undefined,
            scans_p2: row.scans_p2 ?? undefined,
            revealedHiddenMoves: safeParse(row.revealedHiddenMoves, {}, row.id, 'revealedHiddenMoves'),
            newlyRevealed: safeParse(row.newlyRevealed, null, row.id, 'newlyRevealed'),
            justCaptured: safeParse(row.justCaptured, null, row.id, 'justCaptured'),
            hidden_stones_used_p1: row.hidden_stones_used_p1 ?? undefined,
            hidden_stones_used_p2: row.hidden_stones_used_p2 ?? undefined,
            pendingCapture: safeParse(row.pendingCapture, null, row.id, 'pendingCapture'),
            permanentlyRevealedStones: safeParse(row.permanentlyRevealedStones, null, row.id, 'permanentlyRevealedStones'),
            missiles_p1: row.missiles_p1 ?? undefined,
            missiles_p2: row.missiles_p2 ?? undefined,
            missileUsedThisTurn: !!row.missileUsedThisTurn,
            rpsState: safeParse(row.rpsState, null, row.id, 'rpsState'),
            rpsRound: row.rpsRound ?? undefined,
            dice: safeParse(row.dice, null, row.id, 'dice'),
            stonesToPlace: row.stonesToPlace ?? undefined,
            turnOrderRolls: safeParse(row.turnOrderRolls, null, row.id, 'turnOrderRolls'),
            turnOrderRollReady: safeParse(row.turnOrderRollReady, null, row.id, 'turnOrderRollReady'),
            turnOrderRollResult: row.turnOrderRollResult ?? undefined,
            turnOrderRollTies: row.turnOrderRollTies ?? undefined,
            turnOrderRollDeadline: row.turnOrderRollDeadline ?? undefined,
            turnOrderAnimationEndTime: row.turnOrderAnimationEndTime ?? undefined,
            turnChoiceDeadline: row.turnChoiceDeadline ?? undefined,
            turnChooserId: row.turnChooserId ?? undefined,
            turnChoices: safeParse(row.turnChoices, null, row.id, 'turnChoices'),
            turnSelectionTiebreaker: row.turnSelectionTiebreaker ?? undefined,
            diceRollHistory: safeParse(row.diceRollHistory, null, row.id, 'diceRollHistory'),
            diceRoundSummary: safeParse(row.diceRoundSummary, null, row.id, 'diceRoundSummary'),
            lastWhiteGroupInfo: safeParse(row.lastWhiteGroupInfo, null, row.id, 'lastWhiteGroupInfo'),
            diceGoItemUses: safeParse(row.diceGoItemUses, {}, row.id, 'diceGoItemUses'),
            diceGoBonuses: safeParse(row.diceGoBonuses, {}, row.id, 'diceGoBonuses'),
            diceCapturesThisTurn: row.diceCapturesThisTurn ?? undefined,
            diceLastCaptureStones: safeParse(row.diceLastCaptureStones, null, row.id, 'diceLastCaptureStones'),
            round: row.round ?? 1,
            isDeathmatch: !!row.isDeathmatch,
            turnInRound: row.turnInRound ?? 1,
            scores: safeParse(row.scores, {}, row.id, 'scores'),
            thiefPlayerId: row.thiefPlayerId ?? undefined,
            policePlayerId: row.policePlayerId ?? undefined,
            roleChoices: safeParse(row.roleChoices, null, row.id, 'roleChoices'),
            roleChoiceWinnerId: row.roleChoiceWinnerId ?? undefined,
            thiefRoundSummary: safeParse(row.thiefRoundSummary, null, row.id, 'thiefRoundSummary'),
            thiefDiceRollHistory: safeParse(row.thiefDiceRollHistory, null, row.id, 'thiefDiceRollHistory'),
            thiefCapturesThisRound: row.thiefCapturesThisRound ?? undefined,
            alkkagiStones: safeParse(row.alkkagiStones, null, row.id, 'alkkagiStones'),
            alkkagiStones_p1: safeParse(row.alkkagiStones_p1, null, row.id, 'alkkagiStones_p1'),
            alkkagiStones_p2: safeParse(row.alkkagiStones_p2, null, row.id, 'alkkagiStones_p2'),
            alkkagiTurnDeadline: row.alkkagiTurnDeadline ?? undefined,
            alkkagiPlacementDeadline: row.alkkagiPlacementDeadline ?? undefined,
            alkkagiItemUses: safeParse(row.alkkagiItemUses, {}, row.id, 'alkkagiItemUses'),
            activeAlkkagiItems: safeParse(row.activeAlkkagiItems, {}, row.id, 'activeAlkkagiItems'),
            alkkagiRound: row.alkkagiRound ?? undefined,
            alkkagiRefillsUsed: safeParse(row.alkkagiRefillsUsed, {}, row.id, 'alkkagiRefillsUsed'),
            alkkagiStonesPlacedThisRound: safeParse(row.alkkagiStonesPlacedThisRound, {}, row.id, 'alkkagiStonesPlacedThisRound'),
            alkkagiRoundSummary: safeParse(row.alkkagiRoundSummary, null, row.id, 'alkkagiRoundSummary'),
            curlingStones: safeParse(row.curlingStones, null, row.id, 'curlingStones'),
            curlingTurnDeadline: row.curlingTurnDeadline ?? undefined,
            curlingScores: safeParse(row.curlingScores, {}, row.id, 'curlingScores'),
            curlingRound: row.curlingRound ?? undefined,
            curlingRoundSummary: safeParse(row.curlingRoundSummary, null, row.id, 'curlingRoundSummary'),
            curlingItemUses: safeParse(row.curlingItemUses, {}, row.id, 'curlingItemUses'),
            activeCurlingItems: safeParse(row.activeCurlingItems, {}, row.id, 'activeCurlingItems'),
            hammerPlayerId: row.hammerPlayerId ?? undefined,
            isTiebreaker: !!row.isTiebreaker,
            tiebreakerStonesThrown: row.tiebreakerStonesThrown ?? undefined,
            stonesThrownThisRound: safeParse(row.stonesThrownThisRound, {}, row.id, 'stonesThrownThisRound'),
            preGameConfirmations: safeParse(row.preGameConfirmations, null, row.id, 'preGameConfirmations'),
            roundEndConfirmations: safeParse(row.roundEndConfirmations, null, row.id, 'roundEndConfirmations'),
            rematchRejectionCount: safeParse(row.rematchRejectionCount, null, row.id, 'rematchRejectionCount'),
            timeoutFouls: safeParse(row.timeoutFouls, {}, row.id, 'timeoutFouls'),
            curlingStonesLostToFoul: safeParse(row.curlingStonesLostToFoul, {}, row.id, 'curlingStonesLostToFoul'),
            foulInfo: safeParse(row.foulInfo, null, row.id, 'foulInfo'),
            isAnalyzing: !!row.isAnalyzing,
            analysisResult: safeParse(row.analysisResult, null, row.id, 'analysisResult'),
            previousAnalysisResult: safeParse(row.previousAnalysisResult, null, row.id, 'previousAnalysisResult'),
            settings: { ...DEFAULT_GAME_SETTINGS, ...safeParse(row.settings, {}, row.id, 'settings') },
            canRequestNoContest: safeParse(row.canRequestNoContest, null, row.id, 'canRequestNoContest'),
            pausedTurnTimeLeft: row.pausedTurnTimeLeft ?? undefined,
            itemUseDeadline: row.itemUseDeadline ?? undefined,
            lastTimeoutPlayerId: row.lastTimeoutPlayerId ?? undefined,
            lastTimeoutPlayerIdClearTime: row.lastTimeoutPlayerIdClearTime ?? undefined,
            revealAnimationEndTime: row.revealAnimationEndTime ?? undefined,
            revealEndTime: row.revealEndTime ?? undefined,
            isAiGame: !!row.isAiGame,
            aiTurnStartTime: row.aiTurnStartTime ?? undefined,
            mythicBonuses: safeParse(row.mythicBonuses, {}, row.id, 'mythicBonuses'),
            lastPlayfulGoldCheck: safeParse(row.lastPlayfulGoldCheck, {}, row.id, 'lastPlayfulGoldCheck'),
            pendingSystemMessages: safeParse(row.pendingSystemMessages, null, row.id, 'pendingSystemMessages'),
            isSinglePlayer: !!row.isSinglePlayer,
            stageId: row.stageId ?? undefined,
            blackPatternStones: safeParse(row.blackPatternStones, null, row.id, 'blackPatternStones'),
            whitePatternStones: safeParse(row.whitePatternStones, null, row.id, 'whitePatternStones'),
            singlePlayerPlacementRefreshesUsed: row.singlePlayerPlacementRefreshesUsed ?? undefined,
            blackStonesPlaced: row.blackStonesPlaced ?? undefined,
            blackStoneLimit: row.blackStoneLimit ?? undefined,
            isTowerChallenge: !!row.isTowerChallenge,
            floor: row.floor ?? undefined,
            gameType: row.gameType ?? undefined,
            whiteStonesPlaced: row.whiteStonesPlaced ?? undefined,
            whiteStoneLimit: row.whiteStoneLimit ?? undefined,
            autoEndTurnCount: row.autoEndTurnCount ?? undefined,
        };
        return game;
    } catch (e) {
        console.error(`[FATAL] Error processing game data for row ID ${row?.id}:`, e);
        return null;
    }
};